apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-prod
  template:
    metadata:
      labels:
        app: backend-prod
    spec:
      containers:
      - name: backend
        image: ghcr.io/willcataco-los-papus-y-sebas/willcataco-server:prod-65bc5057426f2c636a23b0dbdc65e008dff301e6
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secrets-prod
        env:
        - name: DB_HOST
          value: postgres-prod
        - name: DB_PORT
          value: "5432"
