apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress-prod
spec:
  rules:
  - host: api.willcataco.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-prod
            port:
              number: 80
