apiVersion: apps/v1
kind: Deployment
metadata:
  name: willcataco-prod-frontend
  labels:
    app: willcataco-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willcataco-frontend
      environment: prod
  template:
    metadata:
      labels:
        app: willcataco-frontend
        environment: prod
    spec:
      containers:
        - name: willcataco-frontend
          image: ghcr.io/willcataco-los-papus-y-sebas/willcataco:prod-8eba190c59e8f98ed8fc1464fc3130de43861392
          ports:
            - containerPort: 80