apiVersion: v1
kind: Service
metadata:
  name: willcataco-prod-frontend
spec:
  selector:
    app: willcataco-frontend
    environment: prod
  ports:
    - name: http
      port: 80
      targetPort: 4200
  type: ClusterIP
