apiVersion: apps/v1
kind: Deployment
metadata:
  name: willcataco-dev-frontend
  labels:
    app: willcataco-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willcataco-frontend
      environment: dev
  template:
    metadata:
      labels:
        app: willcataco-frontend
        environment: dev
    spec:
      containers:
        - name: willcataco-frontend
          image: ghcr.io/willcataco-los-papus-y-sebas/willcataco:dev-ff3a3750b5e212802378158a864b45e2a963b328
          ports:
            - containerPort: 80
