apiVersion: apps/v1
kind: Deployment
metadata:
  name: willcataco-dev-frontend
  labels:
    app: willcataco-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willcataco-frontend
      environment: dev
  template:
    metadata:
      labels:
        app: willcataco-frontend
        environment: dev
    spec:
      containers:
        - name: willcataco-frontend
          image: ghcr.io/willcataco-los-papus-y-sebas/willcataco:dev-a0f74ad7cc3d9fbf1ca53c2d31abca20b65687c2
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: willcataco-frontend-dev-env
