apiVersion: apps/v1
kind: Deployment
metadata:
  name: willcataco-dev-frontend
  labels:
    app: willcataco-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willcataco-frontend
      environment: dev
  template:
    metadata:
      labels:
        app: willcataco-frontend
        environment: dev
    spec:
      containers:
        - name: willcataco-frontend
          image: ghcr.io/willcataco-los-papus-y-sebas/willcataco:dev-fdd90bf38f4ca723d248d13551df3e041cbf8a82
          ports:
            - containerPort: 80
