apiVersion: apps/v1
kind: Deployment
metadata:
  name: willcataco-dev-frontend
  labels:
    app: willcataco-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willcataco-frontend
      environment: dev
  template:
    metadata:
      labels:
        app: willcataco-frontend
        environment: dev
    spec:
      containers:
        - name: willcataco-frontend
          image: ghcr.io/willcataco-los-papus-y-sebas/willcataco:dev-492b2832d0b481486a3045895c480af4b5a51876
          ports:
            - containerPort: 80
