apiVersion: apps/v1
kind: Deployment
metadata:
  name: willcataco-dev-frontend
  labels:
    app: willcataco-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willcataco-frontend
      environment: dev
  template:
    metadata:
      labels:
        app: willcataco-frontend
        environment: dev
    spec:
      containers:
        - name: willcataco-frontend
          image: ghcr.io/sudoers-01/willcataco-frontend:dev
          ports:
            - containerPort: 4200
          envFrom:
            - secretRef:
                name: willcataco-frontend-dev-env
