apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: willcataco-dev-frontend
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: dev.willcataco.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: willcataco-dev-frontend
                port:
                  number: 80
