apiVersion: v1
kind: Service
metadata:
  name: willcataco-dev-frontend
spec:
  selector:
    app: willcataco-frontend
    environment: dev
  ports:
    - name: http
      port: 80
      targetPort: 4200
  type: ClusterIP
