apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-dev
  template:
    metadata:
      labels:
        app: backend-dev
    spec:
      containers:
      - name: backend
        image: ghcr.io/willcataco-los-papus-y-sebas/willcataco-server:dev-96f2de2fb6a00947d3db08986cef2d67a14475f8
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secrets-dev
        env:
        - name: DB_HOST
          value: postgres-dev
        - name: DB_PORT
          value: "5432"
