apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress-dev
spec:
  rules:
  - host: dev-api.willcataco.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-dev
            port:
              number: 80
